### ISSUE TITLE
Error in actions.ts

### ISSUE THREAD

**Issue by vagyriag** [InfomediaLtd/angular2-redux#10]
Hi!

I think you have a little error here
https://github.com/InfomediaLtd/angular2-redux/blob/master/src/actions.ts#L17

```if (action && appStore && action instanceof AppStore) {```

shouldn't it be **appStore instanceof AppStore**?

**Comment by rubyboy** [comment]
@vagyriag why do you think it's an error?

This little check is for support the previous version of this function (```constructor(appStore:AppStore,action)```), which accepted an appStore as the first argument and the action as the second. When calling it the code looked like ```counterActions.createDispatcher(appStore,counterActions.increment)```. The new version lets you send a single argument - action - and the AppStore would be injected (or optionally still provided as the second argument).

So, what this code checks is if we have received an action and an appStore arguments, but the action is actually an appStore. So it checks if both exist and if the action is an instance of the AppStore class. If it is then it's an older style call and flips them.
In future versions, if we make some other breaking change I'll take out this code so it's cleaner, but right now it's there to avoid breaking the interface for people who still use the previous signature.

Does that make sense?

**Comment by vagyriag** [comment]
ohhh ok, my bad.
Didn't understand the comment, but it makes sense 

sorry for the trouble

**Comment by rubyboy** [comment]
No worries. Thanks for being proactive on this.
