### ISSUE TITLE
Documention of "unsubscribe"? 

### ISSUE THREAD

**Issue by maku** [InfomediaLtd/angular2-redux#3]
From my point of view, It would a good idea to document how to subscribe / unsubscribe correctly or at least mention that it is necessary.

e.g in a component: 

```
import {AppStore} from 'angular2-redux';

/**
 * Base Component which manages redux store with implementing lifecycle methods
 */
export class StateAwareComponent implements OnDestroy {

    appStoreDisposer: Function;

    constructor(public appStore: AppStore) {
        this.appStoreDisposer = appStore.subscribe(state => {
            this.handleStateSubscription(state);
        });
    }

    handleStateSubscription(state: any): void {
        console.error('handleState method not implemented');
    }

    ngOnDestroy() {
        console.log('destroy called');
        this.appStoreDisposer();
    }
}

```

**Comment by rubyboy** [comment]
@maku very good point. Thanks for pointing this out!

I've added some code to the example app unsubscribing from the app store and also some documentation:
![image](https://cloud.githubusercontent.com/assets/1908166/13285823/b44ef1d4-db05-11e5-9417-dc72a63663d8.png)
