### ISSUE TITLE
debug flag question

### ISSUE THREAD

**Issue by vagyriag** [InfomediaLtd/angular2-redux#5]
Hi! me again

I'm having troubles with that debug flag...
when I navigate to another route it dissapear (as espected) 
I know there are workarrounds but it just doesn't feel right to put that query param everywhere...

is it possible to set the isDebug flag with an optional parameter in the **createAppStoreFactory**? 
something like
```
export function createAppStoreFactory(reducers, additionalMiddlewares = [], shouldDebug?: boolean) {
    return () => {
			const isDebug = shouldDebug && window["devToolsExtension"];
    ....
```
or maybe checking for the global development mode

I also think it's better if the user can't just add 'debug' in the url and access that extra info

thanks for your time!

**Comment by rubyboy** [comment]
@vagyriag  you're absolutely right. I've added an option to specify debug option explicitly in a new createAppStoreWithOptions function: https://github.com/InfomediaLtd/angular2-redux/commit/57036d97e67b9e817252c3d234fb83547dff0e56

You can now either not specify it, provide true/false or pass in a function where you can then perform your own checks if debug is enabled or not (use the angular development mode, etc).

![image](https://cloud.githubusercontent.com/assets/1908166/13727849/d94d319e-e90b-11e5-853d-465c599b9fc5.png)

Let me know if this gives you with what you were after. Thanks heaps for the feedback and suggestion!

**Comment by vagyriag** [comment]
Yeah, awesome! 

thanks
