### ISSUE TITLE
Update siblings peerDependencies requirements

### ISSUE THREAD

**Issue by holpit** [InfomediaLtd/angular2-redux#6]
Hi,
Can you kindly update the project to be compatible with the last version of  redux-thunk@2.0.1 ?

Thanks.

**Comment by rubyboy** [comment]
@holpit Sure, I'll have time to do that over the weekend.
BTW, if you're interested in doing it yourself on a fork and submitting a PR I'll happily walk you through the process and help you with performing the changing and merging it to the master.

**Comment by rubyboy** [comment]
@holpit this has been done. New version released to npm.

Side comment - I noticed some problems with angular2-beta.13 and karma testing. I've left this repository using beta.11 for its internal tests (there is no required peer dependency for angular2).

**Comment by holpit** [comment]
Thank you @rubyboy . Great work.
