### ISSUE TITLE
How to include the package?

### ISSUE THREAD

**Issue by Tuizi** [InfomediaLtd/angular2-redux#7]
Hello I would like to start using angular2-redux.

So in my System.config() I have:

```
paths: {
    "npm:*": "node_modules/*"
},
map: {
    "angular2-redux": "npm:angular2-redux/dist/index.js"
}
```

To be able to do:
import {AppStore, createAppStoreFactory} from "angular2-redux";

But I got this error:
angular2-polyfills.js:332 Error: SyntaxError: Unexpected token <
	Evaluating http://localhost:3000/node_modules/angular2-redux/dist/app-store
	Error loading http://localhost:3000/app/main.js

i know I forgot something, but was is the best way to fix that?

**Comment by divined** [comment]
+1

**Comment by rubyboy** [comment]
You can take a look at the example project that uses angular2-redux: https://github.com/InfomediaLtd/angular2-redux-example
Have you got a different setup than that one? Happy to take a look if you share your project.

**Comment by Tuizi** [comment]
Hello @rubyboy , my configuration is very different, I'm not using jspm for example.

I have solved that by doing, in index.html:

```javascript
        System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                "npm:angular2-redux": {
                    main: 'dist/index.js'
                }
            },
            paths: {
                "npm:*": "node_modules/*"
            },
            map: {
                "angular2-redux": "npm:angular2-redux",
                "redux": "npm:redux/dist/redux.min.js",
                "redux-thunk": "npm:redux-thunk/dist/redux-thunk.min.js"
            }
        });
        System.import('app/main')
                .then(null, console.error.bind(console));
```

**Comment by rubyboy** [comment]
Cool, thanks for posting the code. It may help other people having a similar setup.
