### ISSUE TITLE
Argument of type '{}' is not assignable to parameter of type 'ReducersMapObject'.

### ISSUE THREAD

**Issue by koganei** [InfomediaLtd/angular2-redux#8]
Hi guys,

I'm trying to use this library but after installing typings, when i try to run tsc it gives me the following errors:

```
node_modules/angular2-redux/dist/app-store-factory.ts(49,45): error TS2345: Argument of type '{}' is not assignable to parameter of type 'ReducersMapObject'.
  Index signature is missing in type '{}'.
node_modules/angular2-redux/dist/app-store-factory.ts(54,58): error TS2339: Property 'default' does not exist on type 'IMiddleware<any>'.
node_modules/angular2-redux/dist/app-store-factory.ts(55,57): error TS2339: Property 'default' does not exist on type 'IMiddleware<any>'.
node_modules/angular2-redux/dist/app-store-factory.ts(62,31): error TS2346: Supplied parameters do not match any signature of call target.
```

Also when I install my typings I get the following warning:

```
typings WARN badlocation "github:andrew-w-ross/typings-redux" is a mutable location and may change, consider specifying a commit hash
```

Any idea on what solutions there are for this?
Thanks

**Comment by rubyboy** [comment]
Thanks @koganei for reporting and @Tuizi for fixing. Much appreciated!
I haven't released a new version, but this will be a part of the next one. Let me know if you do need a new patch version released.

**Comment by koganei** [comment]
Hi @rubyboy, a patch version would be great!
Thanks

**Comment by rubyboy** [comment]
You got it. [2.1.1](https://www.npmjs.com/package/angular2-redux) is now deployed to NPM.
